%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# https://blog.csdn.net/weixin_43846627/article/details/116712431
#Intrinsic of "Color" / 1280x720 / {YUYV/RGB8/BGR8/RGBA8/BGRA8/Y8}
#  Width:      	1280
#  Height:     	720
#  PPX:        	635.982971191406
#  PPY:        	364.792755126953
#  Fx:         	642.981872558594
#  Fy:         	642.320678710938
#  Distortion: 	Inverse Brown Conrady
#  distortion_model: plumb_bob
#  Coeffs:     	-0.0530853755772114  	0.0618362724781036  	0.000243115719058551  	-0.000230992809520103  	-0.0197865590453148
#  FOV (deg):  	89.73 x 58.54

# Right Camera calibration and distortion parameters (OpenCV)
Camera1.fx: 642.981872558594
Camera1.fy: 642.320678710938
Camera1.cx: 635.982971191406
Camera1.cy: 364.792755126953

# distortion parameters
# For "plumb_bob", the 5 parameters are: (k1, k2, t1, t2, k3).
Camera1.k1: -0.0530853755772114
Camera1.k2: 0.0618362724781036
Camera1.p1: 0.000243115719058551
Camera1.p2: -0.000230992809520103
Camera1.k3: -0.0197865590453148

# Camera resolution
Camera.width: 1280
Camera.height: 720

# Camera frames per second
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1


#Extrinsic from "Color"	  To	  "Accel" :
#  Rotation Matrix:
#    0.999992         0.00230452      -0.00320497
#    -0.00231031       0.999996        -0.00180473
#    0.0032008        0.00181212       0.999993
#
#  Translation Vector: 0.0288530867546797  0.00733684375882149  0.0157747305929661

# Transformation from left camera to body-frame (imu)
#  这里b是imu的坐标系，Tbc 为左相机到IMU坐标系的变化矩阵。
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [0.999992, 0.00230452, -0.00320497, 0.0288530867546797,
         -0.00231031, 0.999996, -0.00180473, 0.00733684375882149,
         0.0032008, 0.00181212, 0.999993, 0.0157747305929661,
         0.0, 0.0, 0.0, 1.0]

# Do not insert KFs when recently lost
IMU.InsertKFsWhenLost: 0

# IMU noise (Use those from VINS-mono)
IMU.NoiseGyro: 1e-3 # 2.44e-4 #1e-3 # rad/s^0.5
IMU.NoiseAcc: 1e-2 # 1.47e-3 #1e-2 # m/s^1.5
IMU.GyroWalk: 1e-6 # rad/s^1.5
IMU.AccWalk: 1e-4 # m/s^2.5
IMU.Frequency: 200.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------
# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1250

# ORB Extractor: Scale factor between levels in the scale pyramid
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5
Viewer.ViewpointF: 500.0
